# Generated by Django 5.0.6 on 2024-06-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin', models.FloatField()),
                ('home_value', models.FloatField()),
                ('age', models.IntegerField()),
                ('initial_rate', models.FloatField()),
                ('expected_rate', models.FloatField()),
                ('cap_on_interest_rate', models.FloatField()),
                ('initial_loc_growth', models.FloatField()),
                ('principal_limit', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
