# Generated by Django 5.0.6 on 2024-06-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(unique=True)),
                ('rate_3_0', models.FloatField()),
                ('rate_3_125', models.FloatField()),
                ('rate_3_25', models.FloatField()),
                ('rate_3_375', models.FloatField()),
                ('rate_3_5', models.FloatField()),
                ('rate_3_625', models.FloatField()),
                ('rate_3_75', models.FloatField()),
                ('rate_3_875', models.FloatField()),
                ('rate_4_0', models.FloatField()),
            ],
        ),
    ]
